---
# TLS and basic authentication configuration example.
#
# Additionally, a certificate and a key file are needed.
tls_server_config:
  cert_file: /etc/ssl/certs/prometheus.crt
  key_file: /etc/ssl/certs/prometheus.key